### ISSUE TITLE
I don't get it. The examples are 66% incorrect.

### ISSUE THREAD

**Issue by bitcoinmeetups** [jina-ai/clip-as-service#760]
Hello,

I'm MB. A very nice and polite guy.

I don't get it. The examples are 66% incorrect.

The AI thinks there's a woman in the picture. But it's a man.

The AI thinks there are three berries in the picture. But there are four. 

What's up with that?

**Comment by JoanFM** [comment]
Hello @bitcoinmeetups ,

Can you share here the examples that you are referring to? What exactly are the images and texts passed to the CAS?

Also please take into accound that all the models are not 100% perfect.

**Comment by bitcoinmeetups** [comment]
The examples are from the Readme.md file on the front page of the repository. That's why I'm wondering, why use examples where the AI is mostly incorrect?

**Comment by numb3r3** [comment]
We show random, non-cherry picked, predictions of zero-shot CLIP classifiers on examples.

**Comment by ZiniuYu** [comment]
@JoanFM The examples are [here](https://github.com/jina-ai/clip-as-service#visual-reasoning).

@bitcoinmeetups Good catch👍 Those results indeed are not perfect because we are using general models in the examples (i.e. they are not fine-tuned for given inputs). You can also test visual reasoning for other images [here](https://clip-as-service.jina.ai/playground/reasoning/).
