### ISSUE TITLE
Which framework maximizes inference speed ?

### ISSUE THREAD

**Issue by SimJeg** [jina-ai/clip-as-service#877]
Hello, 

Do you have somewhere a speed comparison of the different CLIP models with the following matrix ?
- hardware : T4, V100, A40, A100 etc.
- model : ViT-B, ViT-L, ViT-H etc.
- batch size
- tensor type 
- framework : pytorch JIT, TensorRT, AiTemplate, FasterTransformer by NVIDIA etc.

I am especially interested by the last dimension : which framework / compiler is currently the best to maximize speed of vision transformers ?

Thank you,
Simon

**Comment by jemmyshin** [comment]
For model comparison, we have a benchmark for this: https://clip-as-service.jina.ai/user-guides/benchmark/
Also we are now working on different inference frameworks such as AITemplate / dynamo to find the suitable one for CLIP-as-service.
Unfortunately we are not able to test the metrics on different hardwares since: we don't have sufficient hardware to test it and also some framework doesn't work well on specific hardware (AITemplate onV100).

Does this answer your question?

**Comment by SimJeg** [comment]
Thanks for your feedback, it fills a few cells in the matrix :) I may do
some benchmarks later I don't find the answer. I think TensorRT is the
fastest but need to check
