### ISSUE TITLE
When will it support Python3.11

### ISSUE THREAD

**Issue by learningpro** [jina-ai/clip-as-service#887]
When using python3.11, it can not install clip_server using `pip3 install clip_server`， is there any plan to support latest python version?

**Comment by ZiniuYu** [comment]
Hi @learningpro

Thank you for your inquiry. At this time, `clip_server` does not support Python 3.11 due to some upstream dependencies that are not fully supported in Python 3.11. We are currently investigating potential solutions and updates to the software, so please check back in the future for updates. Thank you for your patience.
